### ISSUE TITLE
Can't access PATCH order

### ISSUE THREAD

**Issue by ThapaMahesh** [commercelayer/commercelayer-checkout#2]
I had to add market scope as the current project doesn't have one which didn't allow access for GET orders. After adding I got the view page but as soon as I change the email, the PATCH request is called. then I get "Access Denied" error back.

Issue with sales channel where there is only client Id. but worked with Integration Api which has both client id and client secret

**Comment by fconforti** [comment]
Hi @ThapaMahesh, I'm not sure I understand. Where did you add the market scope exactly?

**Comment by ThapaMahesh** [comment]
In the environment file and then in the AuthService.js

The document only says to configure _clientID_ with **sales channel** but with that alone, I couldn't load the checkout page. After I added the _market scope_ I was able to load the checkout page (order api GET request). However, the order api for PATCH request failed. 

I tried creating another _application_ with **Integration** kind allowing all the necessary (or those I thought are necessary) access to the role. I added clientId and client secret from that application to environment file and then added _client_secret_ to AuthService.js. With which I was able to work.
However, I think application from **sales channel** (with only clientID and market scope) should have been sufficient to work on checkout.

**Comment by fconforti** [comment]
@ThapaMahesh all you need to do is set the following environment variables:

- **VUE_APP_API_BASE_URL** => your organization endpoint
- **VUE_APP_API_CLIENT_ID** => Your sales channel application client ID

You don't need to specify any market scope, as you are checking out an order that is already associated with a market.

Please note that the sales channel can only manage orders that have a 'draft', 'pending', or 'placed' status. So if you approve (or cancel) the order, the sale channel loses the grants on that order.

Hope it helps.

**Comment by ThapaMahesh** [comment]
I found the issue was with the confusion of **channel** and **sales_channel**. I was using channel for it to work with older application. They seemed similar if not same for me to use with __checkout__ as well.

It works now.

**Comment by fconforti** [comment]
Sorry for the confusion. It was actually quite easy to make a mistake between the **channel** (which is now deprecated) and the **sales_channel** application. Now the documentation is up to date.

Cheers,
F.
